services:
  mongodb:
    image: mongo:latest
    container_name: bel_db
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017

  redis:
    image: redis:latest
    container_name: dumb_redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    expose:
      - 6379

  belphegor:
    image: nguuuquaaa/belphegor:latest
    container_name: belphegor
    command: python run.py
    restart: unless-stopped
    environment:
      LOGGER: belphegor
      LOG_LEVEL: DEBUG
    volumes:
      - .:/bel
    working_dir: /bel
    depends_on:
      - mongodb
      - redis
