version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - data/db:/data/db
    expose:
      - 27017

  bel:
    image: nguuuquaaa/belphegor:latest
    command: python3.10 run.py
    restart: always
    environment:
      - LOGGER=belphegor
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/bel
    working_dir: /bel
    depends_on:
      - db
